# Generated by Django 4.0 on 2021-12-27 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default='', max_length=8, unique=True)),
                ('artist', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=24)),
                ('genre', models.CharField(max_length=12)),
                ('album_image_url', models.URLField()),
                ('preview_url', models.URLField()),
            ],
        ),
    ]
